//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusienssLogic.ServRef_Marcaciones {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eMarcacion", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class eMarcacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODPERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HORAINGRESOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HORASALIDAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODPER {
            get {
                return this.CODPERField;
            }
            set {
                if ((object.ReferenceEquals(this.CODPERField, value) != true)) {
                    this.CODPERField = value;
                    this.RaisePropertyChanged("CODPER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((this.FECHAField.Equals(value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HORAINGRESO {
            get {
                return this.HORAINGRESOField;
            }
            set {
                if ((this.HORAINGRESOField.Equals(value) != true)) {
                    this.HORAINGRESOField = value;
                    this.RaisePropertyChanged("HORAINGRESO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HORASALIDA {
            get {
                return this.HORASALIDAField;
            }
            set {
                if ((this.HORASALIDAField.Equals(value) != true)) {
                    this.HORASALIDAField = value;
                    this.RaisePropertyChanged("HORASALIDA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServRef_Marcaciones.IMarcaciones")]
    public interface IMarcaciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcaciones/GetMarcaciones", ReplyAction="http://tempuri.org/IMarcaciones/GetMarcacionesResponse")]
        BusienssLogic.ServRef_Marcaciones.eMarcacion[] GetMarcaciones(System.DateTime i_fecha_ini, System.DateTime i_fecha_fin, string i_codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMarcacionesChannel : BusienssLogic.ServRef_Marcaciones.IMarcaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarcacionesClient : System.ServiceModel.ClientBase<BusienssLogic.ServRef_Marcaciones.IMarcaciones>, BusienssLogic.ServRef_Marcaciones.IMarcaciones {
        
        public MarcacionesClient() {
        }
        
        public MarcacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarcacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarcacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarcacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusienssLogic.ServRef_Marcaciones.eMarcacion[] GetMarcaciones(System.DateTime i_fecha_ini, System.DateTime i_fecha_fin, string i_codigo) {
            return base.Channel.GetMarcaciones(i_fecha_ini, i_fecha_fin, i_codigo);
        }
    }
}
